In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np 
import time
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import RFE
from sklearn.feature_selection import chi2
from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt
#importing the needed library

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
from sklearn.decomposition import PCA 
def pca(x_train,x_test,n):

    pca = PCA(n_components = n)
    
    x_train = pca.fit_transform(x_train)
    x_test = pca.transform(x_test)
    explained_variance = pca.explained_variance_ratio_

    return x_train, x_test, explained_variance,pca

#we integrated training and test set with standardscalar
def split_scalar(indep_x,dep_y):
    x_train,x_test,y_train,y_test=train_test_split(indep_x,dep_y,test_size=0.25,random_state=0)
    sc=StandardScaler()
    x_train=sc.fit_transform(x_train)
    x_test=sc.transform(x_test)
    return x_train,x_test,y_train,y_test,sc


#we make confusion matrix as a function
def cm_prediction(classifier,x_test):
    y_pred=classifier.predict(x_test)
    from sklearn.metrics import confusion_matrix
    cm=confusion_matrix(y_test,y_pred)
    from sklearn.metrics import accuracy_score
    from sklearn.metrics import classification_report
    accuracy=accuracy_score(y_test,y_pred)
    report=classification_report(y_test,y_pred)
    return classifier,accuracy, report,x_test,y_test,cm
 

def svm_NL(x_train,y_train,x_test):
    from sklearn.svm import SVC
    classifier= SVC(kernel='rbf',random_state=0)
    classifier.fit(x_train,y_train)
    classifier,accuracy, report,x_test,y_test,cm=cm_prediction(classifier,x_test)
    return classifier,accuracy, report,x_test,y_test,cm 




In [4]:
#table Formation
def PCA_classification(accsvmnl):
    dataframe=pd.DataFrame(index=['PCA'],columns=['SVMNL'])
    
    for number, index in enumerate(dataframe.index):
        dataframe['SVMNL'][index]= accsvmnl [number]
        return dataframe

In [5]:
dataset1=pd.read_csv('prep.csv',index_col=None)

In [6]:
df2=dataset1
df2

age         bp sg   al   su     rbc        pc         pcc  \
0     2.000000  76.459948  c  3.0  0.0  normal  abnormal  notpresent   
1     3.000000  76.459948  c  2.0  0.0  normal    normal  notpresent   
2     4.000000  76.459948  a  1.0  0.0  normal    normal  notpresent   
3     5.000000  76.459948  d  1.0  0.0  normal    normal  notpresent   
4     5.000000  50.000000  c  0.0  0.0  normal    normal  notpresent   
..         ...        ... ..  ...  ...     ...       ...         ...   
394  51.492308  70.000000  a  0.0  0.0  normal    normal  notpresent   
395  51.492308  70.000000  c  0.0  2.0  normal    normal  notpresent   
396  51.492308  70.000000  c  3.0  0.0  normal    normal  notpresent   
397  51.492308  90.000000  a  0.0  0.0  normal    normal  notpresent   
398  51.492308  80.000000  a  0.0  0.0  normal    normal  notpresent   

             ba         bgr  ...        pcv            wc        rc  htn   dm  \
0    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
1    notpresent  148.112676  ...  34.000000  12300.000000  4.705597   no   no   
2    notpresent   99.000000  ...  34.000000   8408.191126  4.705597   no   no   
3    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
4    notpresent  148.112676  ...  36.000000  12400.000000  4.705597   no   no   
..          ...         ...  ...        ...           ...       ...  ...  ...   
394  notpresent  219.000000  ...  37.000000   9800.000000  4.400000   no   no   
395  notpresent  220.000000  ...  27.000000   8408.191126  4.705597  yes  yes   
396  notpresent  110.000000  ...  26.000000   9200.000000  3.400000  yes  yes   
397  notpresent  207.000000  ...  38.868902   8408.191126  4.705597  yes  yes   
398  notpresent  100.000000  ...  53.000000   8500.000000  4.900000   no   no   

     cad  appet    pe  ane classification  
0     no    yes   yes   no            yes  
1     no    yes  poor   no            yes  
2     no    yes  poor   no            yes  
3     no    yes  poor  yes            yes  
4     no    yes  poor   no            yes  
..   ...    ...   ...  ...            ...  
394   no    yes  poor   no            yes  
395   no    yes  poor  yes            yes  
396   no   poor  poor   no            yes  
397   no    yes  poor  yes            yes  
398   no    yes  poor   no             no  

[399 rows x 25 columns]

In [7]:
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.expand_frame_repr', False)  # Prevent line breaks

In [8]:
df2=pd.get_dummies(df2,dtype=int,drop_first=True)
indep_x=df2.drop('classification_yes',axis=1)
dep_y=df2['classification_yes']
df2

age         bp   al   su         bgr          bu        sc         sod       pot       hrmo        pcv            wc        rc  sg_b  sg_c  sg_d  sg_e  rbc_normal  pc_normal  pcc_present  ba_present  htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  classification_yes
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356  137.528754  4.627244  12.518156  38.868902   8408.191126  4.705597     0     1     0     0           1          0            0           0        0       0        0          1       1        0                   1
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000  137.528754  4.627244  10.700000  34.000000  12300.000000  4.705597     0     1     0     0           1          1            0           0        0       0        0          1       0        0                   1
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000  138.000000  4.400000  12.000000  34.000000   8408.191126  4.705597     0     0     0     0           1          1            0           0        0       0        0          1       0        0                   1
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000  138.000000  3.200000   8.100000  38.868902   8408.191126  4.705597     0     0     1     0           1          1            0           0        0       0        0          1       0        1                   1
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000  137.528754  4.627244  11.800000  36.000000  12400.000000  4.705597     0     1     0     0           1          1            0           0        0       0        0          1       0        0                   1
..         ...        ...  ...  ...         ...         ...       ...         ...       ...        ...        ...           ...       ...   ...   ...   ...   ...         ...        ...          ...         ...      ...     ...      ...        ...     ...      ...                 ...
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000  139.000000  3.700000  12.500000  37.000000   9800.000000  4.400000     0     0     0     0           1          1            0           0        0       0        0          1       0        0                   1
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000  137.528754  4.627244   8.700000  27.000000   8408.191126  4.705597     0     1     0     0           1          1            0           0        1       1        0          1       0        1                   1
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000  134.000000  2.700000   9.100000  26.000000   9200.000000  3.400000     0     1     0     0           1          1            0           0        1       1        0          0       0        0                   1
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000  142.000000  5.500000   8.500000  38.868902   8408.191126  4.705597     0     0     0     0           1          1            0           0        1       1        0          1       0        1                   1
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000  140.000000  5.000000  16.300000  53.000000   8500.000000  4.900000     0     0     0     0           1          1            0           0        0       0        0          1       0        0                   0

[399 rows x 28 columns]

In [9]:
x_train,x_test,y_train,y_test,sc=split_scalar(indep_x,dep_y)

In [10]:

x_train, x_test, explained_variance,pca=pca(x_train,x_test,2)

accsvmnl=[]

In [11]:
x_train

array([[-2.51286761e-01,  3.78566106e-01],
       [-1.33765785e+00,  5.04725675e-01],
       [-2.57133641e+00,  2.27936734e-01],
       [ 3.98129474e+00,  3.17919703e+00],
       [-2.78756511e+00, -3.93739316e-01],
       [ 1.90679415e+00,  9.69126837e-01],
       [-2.61690681e+00,  1.61114482e-01],
       [ 1.07474924e+00, -1.86068660e+00],
       [-2.69917057e+00, -1.87226521e-01],
       [ 1.89127694e+00,  7.51971129e-01],
       [ 2.46516761e+00, -1.50538507e+00],
       [-2.47081218e+00,  7.99218652e-02],
       [-1.29958317e+00,  8.49242218e-01],
       [-2.72436339e+00,  9.61403716e-01],
       [ 3.01709938e+00, -3.59825973e+00],
       [ 8.14973946e+00,  1.63363156e+00],
       [ 7.26250706e-01,  1.60213274e+00],
       [-3.07280868e+00, -3.37051153e-01],
       [-2.75890410e+00, -9.89034064e-03],
       [-2.31814131e+00,  2.95205892e-01],
       [ 1.91864455e+00, -2.31777234e-02],
       [-2.34439088e+00, -1.11270293e-01],
       [ 5.20950717e+00,  9.56666170e-01],
       [-2.

In [12]:
x_test

array([[-3.43850809,  0.10572892],
       [ 0.89015203, -0.79392271],
       [-2.58112498, -0.1522395 ],
       [ 2.05328575, -2.00940148],
       [ 0.70755363, -0.44122136],
       [ 1.01058442, -1.56123328],
       [ 5.95275491,  1.23619484],
       [ 0.33916118, -2.39169819],
       [-2.26284986, -0.27908238],
       [-2.81913582,  0.20973458],
       [-1.48199589, -1.97537903],
       [-0.09739493,  1.12159262],
       [-3.04120362,  0.0075242 ],
       [ 2.83185787, -2.50093418],
       [-2.90465022,  0.37072307],
       [-2.55184971,  0.16149561],
       [ 0.30210088, -0.81394025],
       [-2.6329207 ,  0.30607473],
       [ 2.76363471,  0.64412193],
       [ 4.08412105, -2.9073801 ],
       [-2.22035614,  0.39000988],
       [ 1.87025755, -0.36773609],
       [ 1.32844045, -0.25467722],
       [-2.41325066, -0.23835513],
       [ 6.1884747 ,  2.75145376],
       [-2.28559988, -0.12269803],
       [-3.47715352,  0.3903668 ],
       [-3.43507174,  0.47527774],
       [ 2.81101801,

In [13]:
explained_variance

array([0.25980804, 0.07304735])

In [14]:
pca

PCA(n_components=2)

In [15]:
classifier,accuracy, report,x_test,y_test,cm=svm_NL(x_train,y_train,x_test)
accsvmnl.append(accuracy)
result=PCA_classification(accsvmnl)

In [16]:
result
#2

SVMNL
PCA     1

In [17]:
import pickle as pkl
filename="finalized_model_svmnl.sav"

In [18]:
pickle.dump(classifier,open(filename,'wb'))

In [19]:
filenamex="sc.pkl"

In [20]:
pickle.dump(sc,open(filenamex,'wb'))

In [21]:
sc=pickle.load(open("sc.pkl",'rb'))

In [22]:
filenamey="pca.pkl"

In [23]:
pickle.dump(pca,open(filenamey,'wb'))

In [24]:
pca=pickle.load(open("pca.pkl",'rb'))

In [25]:
new_input = ([[5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,38.868902,8408.191126,4.705597,0,0,1,0,1,1,0,0,0,0,0,1,0,1]])

In [26]:
scaled_input = sc.transform(new_input)  
pca_input = pca.transform(scaled_input)

In [27]:

loaded_model=pickle.load(open("finalized_model_svmnl.sav",'rb')) 
result = loaded_model.predict(pca_input)

In [28]:
result

array([1])